### ISSUE TITLE
PRESTASHOP

### ISSUE THREAD

**Issue by kristonita18** [iaw-asir-iescelia/glosario#136]
PrestaShop es un sistema gestor de contenidos (CMS) libre y de código abierto, orientado principalmente a la creación de tiendas en línea de comercio electrónico (de ahí su denominación de Shop, tienda ).

Está basado en PHP, MySQL y Smarty.
PrestaShop está disponible bajo la licencia Open Software. El software está escrito en PHP y basado en el motor de plantillas Smarty. MySQL1 es el motor de base de datos predeterminado.
Se puede disponer de versiones en 63 idiomas, entre ellos: inglés, francés, holandés, portugués, alemán, español, italiano, polaco y ruso.
El software hace uso extensivo de AJAX en el panel de administración, mientras que los bloques de módulos pueden ser fácilmente añadidos a la tienda con el fin proporcionar funcionalidad adicional; estos normalmente están proporcionados de forma gratuita por los desarrolladores independientes
Prestashop es compatible con las pasarelas de pago más usuales. También se ofrecen módulos de pago adicionales en el mercado.
Fuente: https://es.wikipedia.org/wiki/PrestaShop

**Comment by josejuansanchez** [comment]
@kristonita18 La definición es correcta, pero tienes que incluirla al archivo README.md del repositorio.

¡Gracias!
